from PIL import Image
import numpy as np
import io

def hide_data(image_bytes: bytes, secret_message: str) -> bytes:
    """
    Hides a secret message inside the least significant bits (LSB) of an image.
    """
    image = Image.open(io.BytesIO(image_bytes))
    
    # Always normalize to RGB to ensure strict 3-channel handling for LSB consistency
    image = image.convert('RGB')
    img_arr = np.array(image, dtype=np.uint8)
    
    # Append delimiter to mark the end of the message
    secret_message += "#####"
    
    # Convert message to a continuous binary string
    binary_msg = ''.join(format(ord(char), '08b') for char in secret_message)
    length = len(binary_msg)
    
    height, width, channels = img_arr.shape
    total_capacity = height * width * channels
    
    if length > total_capacity:
        raise ValueError("Error: Image is too small to hold this secret message!")
        
    # Flatten the image array for vectorized LSB manipulation
    flat_arr = img_arr.reshape(-1)
    
    # Convert binary message string into a numpy array of integers (0 or 1)
    bit_array = np.array([int(b) for b in binary_msg], dtype=np.uint8)
    
    # Clear the least significant bit of the required pixels and set it to the message bits
    flat_arr[:length] = (flat_arr[:length] & 254) | bit_array
    
    # Reshape back to original image dimensions
    encoded_img_arr = flat_arr.reshape((height, width, channels))
    
    encoded_img = Image.fromarray(encoded_img_arr, 'RGB')
    
    output_io = io.BytesIO()
    # Save as PNG to avoid lossy compression artifacts destroying LSB data
    encoded_img.save(output_io, format="PNG")
    return output_io.getvalue()

def extract_data(image_bytes: bytes) -> str:
    """
    Extracts a hidden secret message from the least significant bits (LSB) of an image.
    """
    image = Image.open(io.BytesIO(image_bytes))
    
    if image.format != "PNG":
        raise ValueError("Please upload the exact PNG stego image generated by this tool. Other compressed formats destroy hidden LSB data.")
        
    image = image.convert('RGB')
    img_arr = np.array(image, dtype=np.uint8)
    
    # Flatten array to quickly extract LSBs
    flat_arr = img_arr.reshape(-1)
    lsbs = flat_arr & 1
    
    # Pack bits into bytes efficiently using numpy packbits
    # Note: packbits expects multiple of 8, so we truncate to the nearest full byte
    truncated_len = (len(lsbs) // 8) * 8
    byte_array = np.packbits(lsbs[:truncated_len])
    
    # Decode bytes to characters and check for the termination sequence
    decoded_text = ""
    for byte in byte_array:
        char = chr(byte)
        decoded_text += char
        if decoded_text.endswith("#####"):
            return decoded_text[:-5]
            
    return decoded_text

def get_difference_map(original_bytes: bytes, stego_bytes: bytes) -> Image.Image:
    """
    Generates a visual difference map highlighting the altered LSB pixels.
    """
    img1 = Image.open(io.BytesIO(original_bytes)).convert('RGB')
    img2 = Image.open(io.BytesIO(stego_bytes)).convert('RGB')
    
    arr1 = np.array(img1, dtype=np.int16)
    arr2 = np.array(img2, dtype=np.int16)
    
    # Calculate absolute difference
    diff = np.abs(arr1 - arr2)
    
    # Amplify the 1-bit difference (0 or 1) up to 255 so it becomes clearly visible as white pixels
    diff_scaled = np.clip(diff * 255, 0, 255).astype(np.uint8)
    
    return Image.fromarray(diff_scaled, 'RGB')